name: LSIF
on:
  - push
jobs:
  lsif-go:
    runs-on: ubuntu-latest
    container: sourcegraph/lsif-go
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
      - name: Generate LSIF data
        run: lsif-go
      - name: Upload LSIF data
        run: src lsif upload -github-token=${{ secrets.GITHUB_TOKEN }}
